---
# Build Manifest Configuration
# This file defines the requirements for all build manifests in the Ultimate Blueprint Pilot

build_manifest_required: true
build_manifest_spec:
  required_fields:
    - build_version
    - build_date
    - stack
    - modules
    - external_dependencies
    - doctrine_reference
    - design_notes
    - build_agent
  
  format: "YAML"
  file_name: "build_manifest.yaml"
  
  validation_rules:
    - "No build complete without manifest"
    - "No build approved without commander sign-off on manifest"
    - "Manifest must be human- and machine-readable YAML/JSON"
    - "All required fields must be present and valid"
    - "Build version must follow semantic versioning"
    - "Build date must be in ISO format (YYYY-MM-DD)"
    - "Stack must include framework and hosting information"
    - "Modules must include all active module paths"
    - "External dependencies must be listed as array"
    - "Doctrine reference must match current doctrine version"
    - "Design notes must provide architectural context"
    - "Build agent must identify the AI/IDE used"

  quality_gates:
    - "Manifest validation passes"
    - "Commander sign-off received"
    - "All required fields populated"
    - "Build version incremented"
    - "Deployment successful"

  enforcement:
    - "Build process blocked without valid manifest"
    - "Deployment blocked without commander approval"
    - "Version control requires manifest commit"
    - "CI/CD pipeline validates manifest"

metadata:
  created_at: "2024-01-15T14:57:00.000Z"
  updated_at: "2024-01-15T14:57:00.000Z"
  created_by: "commander@example.com"
  version: "1.0.0"
  doctrine_reference: "nuclear_doctrine_v1.2" 